server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always